const initialWasteRecords = [
  {
    tagId: 'MW-2026-1001',
    category: 'Yellow',
    department: 'Operating Theater',
    weightKg: 6.4,
    status: 'Logged',
    handlerName: 'Nurse Sarah Jenkins',
    location: 'OT-2 Scrub & Prep',
    hazardLevel: 'High-Risk Anatomical',
    notes: 'Surgical dressings, anatomical tissue post-appendectomy.',
    createdAt: new Date(Date.now() - 3600 * 1000 * 3).toISOString(),
    updatedAt: new Date(Date.now() - 3600 * 1000 * 3).toISOString(),
  },
  {
    tagId: 'MW-2026-1002',
    category: 'Red',
    department: 'ICU',
    weightKg: 4.8,
    status: 'Awaiting Pickup',
    handlerName: 'Dr. Aaron Patel',
    location: 'ICU Bed 14 Isolation',
    hazardLevel: 'Bio-Infectious',
    notes: 'Contaminated IV tubing, saline bottles, catheter bags.',
    createdAt: new Date(Date.now() - 3600 * 1000 * 5).toISOString(),
    updatedAt: new Date(Date.now() - 3600 * 1000 * 2).toISOString(),
  },
  {
    tagId: 'MW-2026-1003',
    category: 'White',
    department: 'Emergency',
    weightKg: 2.1,
    status: 'Awaiting Pickup',
    handlerName: 'Tech Carlos Mendez',
    location: 'ER Trauma Bay 1',
    hazardLevel: 'Sharp Hazard',
    notes: 'Puncture-proof container filled with scalpels, hypodermic needles, suture blades.',
    createdAt: new Date(Date.now() - 3600 * 1000 * 7).toISOString(),
    updatedAt: new Date(Date.now() - 3600 * 1000 * 2).toISOString(),
  },
  {
    tagId: 'MW-2026-1004',
    category: 'Blue',
    department: 'Pathology Lab',
    weightKg: 3.7,
    status: 'Logged',
    handlerName: 'Lab Analyst Priya Rao',
    location: 'Histology Section 3B',
    hazardLevel: 'Bio-Infectious',
    notes: 'Broken culture vials, reagent ampoules, specimen slides.',
    createdAt: new Date(Date.now() - 3600 * 1000 * 4).toISOString(),
    updatedAt: new Date(Date.now() - 3600 * 1000 * 4).toISOString(),
  },
  {
    tagId: 'MW-2026-1005',
    category: 'Yellow',
    department: 'Oncology',
    weightKg: 5.2,
    status: 'In Transit',
    handlerName: 'Nurse David Kim',
    location: 'Chemo Infusion Suite 4',
    hazardLevel: 'Toxic Chemical',
    notes: 'Cytotoxic drug administration kits, contaminated absorbent pads.',
    createdAt: new Date(Date.now() - 3600 * 1000 * 12).toISOString(),
    updatedAt: new Date(Date.now() - 3600 * 1000 * 1).toISOString(),
  },
  {
    tagId: 'MW-2026-1006',
    category: 'Red',
    department: 'General Ward',
    weightKg: 7.9,
    status: 'Disposed',
    handlerName: 'Attendant Maya Lin',
    location: 'Ward 3 Clean Utility',
    hazardLevel: 'Bio-Infectious',
    notes: 'Plastic blood collection vacuum tubes, rubber gloves.',
    createdAt: new Date(Date.now() - 3600 * 1000 * 24).toISOString(),
    updatedAt: new Date(Date.now() - 3600 * 1000 * 10).toISOString(),
    disposedAt: new Date(Date.now() - 3600 * 1000 * 10).toISOString(),
  },
  {
    tagId: 'MW-2026-1007',
    category: 'White',
    department: 'Operating Theater',
    weightKg: 1.8,
    status: 'Disposed',
    handlerName: 'Nurse Sarah Jenkins',
    location: 'OT-1 Sharps Bin',
    hazardLevel: 'Sharp Hazard',
    notes: 'Orthopedic drill bits, bone trocars, surgical needles.',
    createdAt: new Date(Date.now() - 3600 * 1000 * 30).toISOString(),
    updatedAt: new Date(Date.now() - 3600 * 1000 * 8).toISOString(),
    disposedAt: new Date(Date.now() - 3600 * 1000 * 8).toISOString(),
  },
  {
    tagId: 'MW-2026-1008',
    category: 'Blue',
    department: 'Emergency',
    weightKg: 4.2,
    status: 'Awaiting Pickup',
    handlerName: 'Tech Carlos Mendez',
    location: 'ER Med Room B',
    hazardLevel: 'Bio-Infectious',
    notes: 'Antibiotic infusion bottles, empty glass anesthesia vials.',
    createdAt: new Date(Date.now() - 3600 * 1000 * 6).toISOString(),
    updatedAt: new Date(Date.now() - 3600 * 1000 * 1).toISOString(),
  }
];

const initialPickups = [
  {
    manifestNumber: 'MAN-2026-0089',
    treatmentFacility: 'Apex Bio-Clean & Incineration Services (CBWTF)',
    vehicleNumber: 'WB-04-E-8821',
    driverName: 'Robert Langdon',
    driverPhone: '+1 (555) 349-8821',
    wasteRecordIds: ['MW-2026-1005'],
    totalWeightKg: 5.2,
    status: 'En Route',
    scheduledDate: new Date(Date.now() - 3600 * 1000 * 2).toISOString(),
    notes: 'Special temperature-controlled transport for cytotoxic oncology residues.',
  },
  {
    manifestNumber: 'MAN-2026-0088',
    treatmentFacility: 'Apex Bio-Clean & Incineration Services (CBWTF)',
    vehicleNumber: 'WB-04-E-1044',
    driverName: 'Michael Turner',
    driverPhone: '+1 (555) 761-4402',
    wasteRecordIds: ['MW-2026-1006', 'MW-2026-1007'],
    totalWeightKg: 9.7,
    status: 'Completed',
    scheduledDate: new Date(Date.now() - 3600 * 1000 * 26).toISOString(),
    completedDate: new Date(Date.now() - 3600 * 1000 * 8).toISOString(),
    notes: 'Autoclaving and microwave shredding completed with certified certificate #CERT-994.',
  }
];

const initialIncidents = [
  {
    incidentId: 'INC-2026-012',
    type: 'Needle-Stick / Sharp Injury',
    department: 'Emergency',
    severity: 'High',
    reportedBy: 'Staff Nurse Elena Rostova',
    reportedDate: new Date(Date.now() - 3600 * 1000 * 48).toISOString(),
    description: 'Accidental superficial needle prick while transferring uncapped 21G syringe into sharps box.',
    correctiveAction: 'Immediate post-exposure prophylaxis (PEP) initiated, tetanus booster administered, re-trained ward staff on "no recapping" rule.',
    status: 'Resolved',
  },
  {
    incidentId: 'INC-2026-015',
    type: 'Bag Puncture / Leak',
    department: 'Operating Theater',
    severity: 'Moderate',
    reportedBy: 'Housekeeping Lead Marcus Cole',
    reportedDate: new Date(Date.now() - 3600 * 1000 * 18).toISOString(),
    description: 'Yellow infectious waste bag developed a pinhole puncture during corridor transit; minimal moisture seepage.',
    correctiveAction: 'Double-bagged immediately, floor sterilized with 1% sodium hypochlorite, reinforced maximum 3/4 fill rule.',
    status: 'Resolved',
  }
];

module.exports = {
  initialWasteRecords,
  initialPickups,
  initialIncidents,
};
